### ISSUE TITLE
pom reference is relative, cannot load a pom within emacs+ensime

### ISSUE THREAD

**Issue by davidsiefert** [zen0wu/sbt-maven-plugin#14]
java.lang.AssertionError: assertion failed: [/tmp/ensime_update_31930x7c/./pom.xml] doesn't exist

I think maybe we just need to change the reference from relative to absolute?  Working on a fix.

**Comment by davidsiefert** [comment]
Woops, wanted to include this too:
        at scala.Predef$.assert(Predef.scala:179)
        at com.github.shivawu.sbt.maven.Pom$.apply(Pom.scala:236)
        at com.github.shivawu.sbt.maven.MavenPlugin$.<init>(MavenPlugin.scala:16)
        at com.github.shivawu.sbt.maven.MavenPlugin$.<clinit>(MavenPlugin.scala)
